[
    {
        "title":'Dilwale',
        "releaseYear":'2015',
        "averageRating":6.6,
        "totalCounting":11,
        "image":'https://image.tmdb.org/t/p/w500//pYgPu6hhOr61knwbestTx4vSdMb.jpg'
    },
    {
        "title":'Brahmāstra Part One: Shiva',
        "releaseYear":'2022',
        "averageRating":6.692,
        "totalCounting":2000,
        "image":'https://image.tmdb.org/t/p/w500//x61qdvHIsr9U53FwoLVDQqAGur0.jpg'
    },
    {
        "title":'Thappad',
        "releaseYear":'2020',
        "averageRating":7.16,
        "totalCounting":1500,
        "image":'https://image.tmdb.org/t/p/w500//4NSjlaYhOZRJzsaxsF6KU4BEXE9.jpg'
    },
    {
        "title":'Kal Ho Naa Ho',
        "releaseYear":'2003',
        "averageRating":7.428,
        "totalCounting":1100,
        "image":'https://image.tmdb.org/t/p/w500//zhMI6I0kSLnewTMwE0A8Tz3Cj2f.jpg'
    },
    {
        "title":'K.G.F: Chapter 1',
        "releaseYear":'2018',
        "averageRating":7.428,
        "totalCounting":1700,
        "image":'https://image.tmdb.org/t/p/w500//ltHlJwvxKv7d0ooCiKSAvfwV9tX.jpg'
    },
    {
        "title":'RRR',
        "releaseYear":'2022',
        "averageRating":7.8,
        "totalCounting":11000,
        "image":'https://image.tmdb.org/t/p/w500//nEufeZlyAOLqO2brrs0yeF1lgXO.jpg'
    },
    {
        "title":'Saaho',
        "releaseYear":'2019',
        "averageRating":7.2,
        "totalCounting":9000,
        "image":'https://image.tmdb.org/t/p/w500//rWXIpR2uPkwb1Hrhjj2FA62FGdu.jpg'
    },
    {
        "title":'Baghban',
        "releaseYear":'2003',
        "averageRating":6.75,
        "totalCounting":1600,
        "image":'https://image.tmdb.org/t/p/w500//p6NPup58fPjIEAU9tKU4XpQhtTA.jpg'
    },
    {
        "title":'Baaghi',
        "releaseYear":'2016',
        "averageRating":6.5,
        "totalCounting":2000,
        "image":'https://image.tmdb.org/t/p/w500//o5VJiWgGp1O2OtjESZVd37gepYQ.jpg'
    },
    {
        "title":'Shivaay',
        "releaseYear":'2016',
        "averageRating":5.8,
        "totalCounting":2505,
        "image":'https://image.tmdb.org/t/p/w500//74CfUuZ5gVC7YwYAfbo38yRGAeD.jpg'
    },
    {
        "title":'Drishyam',
        "releaseYear":'2015',
        "averageRating":7.71,
        "totalCounting":2010,
        "image":'https://image.tmdb.org/t/p/w500//gIClWRv5OSe8rl5Koi0AeUcCZ9Z.jpg'
    },
    {
        "title":'Narvik',
        "releaseYear":'2022',
        "averageRating":6.826,
        "totalCounting":6000,
        "image":'https://image.tmdb.org/t/p/w500//gU4mmINWUF294Wzi8mqRvi6peMe.jpg'
    },
    {
        "title":'Avatar: The Way of Water',
        "releaseYear":'2022',
        "averageRating":7.728,
        "totalCounting":66000,
        "image":'https://image.tmdb.org/t/p/w500//t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'
    },
    {
        "title":'Black Adam',
        "releaseYear":'2022',
        "averageRating":7.719,
        "totalCounting":11000,
        "image":'https://image.tmdb.org/t/p/w500//pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg'
    },
    {
        "title":'Black Panther: Wakanda Forever',
        "releaseYear":'2022',
        "averageRating":7.2,
        "totalCounting":18200,
        "image":'https://image.tmdb.org/t/p/w500//sv1xJUazXeYqALzczSZ3O6nkH75.jpg'
    },
    {
        "title":'Dolphin Boy',
        "releaseYear":'2022',
        "averageRating":6.417,
        "totalCounting":11000,
        "image":'https://image.tmdb.org/t/p/w500//gISoDEiaUH9BNEunmLC7FgUVaia.jpg'
    },
    {
        "title":'Prey for the Devil',
        "releaseYear":'2022',
        "averageRating":7.16,
        "totalCounting":1800,
        "image":'https://image.tmdb.org/t/p/w500//iCvgemXf2Kpr2LvpDmt5J9NhjKM.jpg'
    },
    {
        "title":'Fullmetal Alchemist: The Final Alchemy',
        "releaseYear":'2022',
        "averageRating":6.327,
        "totalCounting":16000,
        "image":'https://image.tmdb.org/t/p/w500//AeyiuQUUs78bPkz18FY3AzNFF8b.jpg'
    },
    {
        "title":'Die Hart',
        "releaseYear":'2023',
        "averageRating":6.414,
        "totalCounting":23000,
        "image":'https://image.tmdb.org/t/p/w500//1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg'
    },
    {
        "title":'All the Places',
        "releaseYear":'2023',
        "averageRating":6.414,
        "totalCounting":11020,
        "image":'https://image.tmdb.org/t/p/w500//1mdYZDqYcRjD4yF8MCh8OPtXApI.jpg'
    },
    {
        "title":'Dragon Knight',
        "releaseYear":'2022',
        "averageRating":6.624,
        "totalCounting":8000,
        "image":'https://image.tmdb.org/t/p/w500//zkGFADykBtfPfTv7YJooxTH52ph.jpg'
    },
    {
        "title":'Krrish 3',
        "releaseYear":'2013',
        "averageRating":5.7,
        "totalCounting":12000,
        "image":'https://image.tmdb.org/t/p/w500//tpCrYKO0S6jIc4qf2rif4J4U4lh.jpg'
    },
    {
        "title":'Fast & Furious Presents: Hobbs & Shaw',
        "releaseYear":'2019',
        "averageRating":6.867,
        "totalCounting":35000,
        "image":'https://image.tmdb.org/t/p/w500//qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg'
    },
    {
        "title":'Gandhada Gudi',
        "releaseYear":'2022',
        "averageRating":7,
        "totalCounting":40000,
        "image":'https://image.tmdb.org/t/p/w500//jCnCNJwyXQsZn0wn0tNkvjMyeN8.jpg'
    },
    {
        "title":'In His Shadow',
        "releaseYear":'2023',
        "averageRating":6.458,
        "totalCounting":28000,
        "image":'https://image.tmdb.org/t/p/w500//ooyH5mGWvN3ZJOSqTBntlQ8Iail.jpg'
    },
    {
        "title":'Haseen Dillruba',
        "releaseYear":'2021',
        "averageRating":6.462,
        "totalCounting":15200,
        "image":'https://image.tmdb.org/t/p/w500//aq1y0tqiH1ojIAQBbxZXFbArEAy.jpg'
    }
]